### ISSUE TITLE
Program crashes when attempting to load files

### ISSUE THREAD

**Issue by Masamune3210** [nicoboss/nsz#102]
Anytime I try to load any file, the program crashes with a traceback complaining about 'int' object is not scriptable. This is with 4.0.1 of the Windows portable builds, I would try the py version but it seems that piwin32 isnt supported on Python 3.10.0?

![image](https://user-images.githubusercontent.com/1053504/136493788-05831baf-6530-4dc8-aa56-ad79c3d1523d.png)

**Comment by nicoboss** [comment]
This should now be fixed on latest release. If the issue still occurs for you, please let me know and I will repopen this issue. pywin32 works perfectly fine on Python 3.10.6 as far I can tell.
