### ISSUE TITLE
Attempting to compress nsp to nsz results in header += fs.cryptokey error

### ISSUE THREAD

**Issue by Masamune3210** [nicoboss/nsz#103]
Any file I feed to nsz fails to start compressing or even creating the file with a TypeError: Can't convert NoneType to bytes. I have all the prodkeys dumped from my own system, and I know the file is laid out correctly as NSC_Builder uses it just fine on the windows side, but nsz seemingly cant find its key? Is the program sensitive to line endings? I couldn't find anything about it so I set them to Unix line endings just in case but it didn't change anything
![image](https://user-images.githubusercontent.com/1053504/137985776-94cc3a65-82db-466d-b8e9-835b122edf2a.png)

**Comment by Masamune3210** [comment]
Think I found the issue but not closing until I can verify that it fixes it. Could it be that I'm missing the titlekey for the title in question? I am building multicontent files using NSC_Builder and then feeding them to nsz to compress them, but if I use its normal setting nsz complains about missing tickets, and if I use the unmodified setting nsz complains that I'm missing the titlekey. Not sure exactly how to resolve this, is there a format guideline for the title.keys file so I can check mine anywhere?

**Comment by Masamune3210** [comment]
I seem to have gotten it fixed, think it was just some misconfigured files or something because its working now, only error I get is the program complaining about master_key0b and 0c, have they been added to nsz yet? Because I'm fairly sure my prod.keys is correct

**Comment by nicoboss** [comment]
Great to hear that everything is working for you now. New master keys 0b and 0c finally got added now: https://github.com/nicoboss/nsz/pull/104
