### ISSUE TITLE
can't install it

### ISSUE THREAD

**Issue by frans4080** [nicoboss/nsz#109]
whenever i try to install this repository it gives me this error  error: subprocess-exited-with-error

**Comment by nicoboss** [comment]
How and on what operating system are you trying to install this application? Are you using latest Windows binary release, the PIP Package or latest master? I think the error "subprocess-exited-with-error" is from PIP if you try installing NSZ on a Python version where certain dependencies needs to be built from source and PIP fails to do so. Can you give me your Python version and the full output of PIP in that case? Once you give me enough information to recreate the issue, I will try fix it.
