### ISSUE TITLE
Some files cannot be compressed ( gives exception )

### ISSUE THREAD

**Issue by plato79** [nicoboss/nsz#11]
When compressing some files ( I found two such files ) nsz.py gives an exception..

While I'm not sure why this happens ( partNr is increased but there is nothing left to read? ) this causes compressing an entire folder to stop. I made some dirty modifications to stop raising this error and delete corrupted destination file so it will continue to process the folder, but you could find the root cause of this problem I think.

Here is the exception:

```
Adding file 7dfaaf90125b66824e14151d5744462f.cnmt.nca 4096 bytes to NSP
Adding file 5243655b68ed240487ab2977f3464d1b.ncz 252821504 bytes to NSP
  0%|                                                                                                                                                                         | 53.3k/253M [00:00<00:00, 568MB/s/s]
list index out of range
nut exception: list index out of range
Traceback (most recent call last):
  File "nsz.py", line 100, in <module>
    nut.compress(filePath, 17 if args.level is None else args.level, args.block, args.bs, args.output, args.threads, args.overwrite)
  File "/usr/home/media/mydev/nsz/compressor/nut/__init__.py", line 11, in compress
    SolidCompressor.solidCompress(filePath, compressionLevel, outputDir, threads, overwrite)
  File "/usr/home/media/mydev/nsz/compressor/nut/SolidCompressor.py", line 101, in solidCompress
    buffer = partitions[partNr].read(CHUNK_SZ)
IndexError: list index out of range```

**Comment by nicoboss** [comment]
Thanks for reporting. I wasn't able to reproduce your issue so far. Could you please post a list of games which causes this issue to occur so I can reproduce and fix it?

**Comment by plato79** [comment]
Let me see, I think one of them was Yooka Laylee Impossible Lair update in JP language, and another was Spaceland update. Spaceland[010034800FB60800][GB][v65536].nsp, I'm certain of that.

**Comment by nicoboss** [comment]
That error message means that your keys.txt file is outdated and doesn’t contain the keys required to decrypt the NCA. I highly recommend to always dump the latest keys after every firmware update so all your dumped games can be decrypted. A better understandable error message for errors caused by using outdated keys.txt was added in nsZip 2.0 which was released release yesterday.

Please dump your keys.txt using https://github.com/shchmue/Lockpick_RCM/releases and try if that solved your issue.

Proof that solid compression works with the latest keys.txt:
```
[ADDING]     7dfaaf90125b66824e14151d5744462f.cnmt.nca 4096 bytes to NSP
[ADDING]     5243655b68ed240487ab2977f3464d1b.ncz 252821504 bytes to NSP
253MB/s [03:18, 1.34MB/s/s]
compressed 75% 252821504 -> 190170307  - 5243655b68ed240487ab2977f3464d1b.nca
[ADDING]     7ccce8345728dd143486f2aa9a95a2d5.nca 1513984 bytes to NSP
[ADDING]     543c3d9bdc95d8ba1eac4f265b752537.nca 166912 bytes to NSP
[ADDING]     010034800fb60800000000000000000a.tik 704 bytes to NSP
[ADDING]     010034800fb60800000000000000000a.cert 1792 bytes to NSP
```

Proof that the integrity of the compressed files isn't violated:
```
[VERIFY NSZ] Spaceland_010034800FB60800_v65536.nsz
[EXISTS]     7dfaaf90125b66824e14151d5744462f.cnmt.nca
253MB/s [00:04, 58.3MB/s/s]
[VERIFIED]   5243655b68ed240487ab2977f3464d1b.ncz
[VERIFIED]   7ccce8345728dd143486f2aa9a95a2d5.nca
[VERIFIED]   543c3d9bdc95d8ba1eac4f265b752537.nca
[EXISTS]     010034800fb60800000000000000000a.tik
[EXISTS]     010034800fb60800000000000000000a.cert
```

**Comment by plato79** [comment]
Sure enough, I updated the keys.txt and it's working now 👍 . Though dumping instead of saying that the key is old is confusing..

**Comment by plato79** [comment]
Got another error, but this time I don't think the problem is in the keys.txt file..

The file this time is "Monaco Complete Edition[010007300DE1E800][US][v65536].nsp"

Here is the dump:

```
1836345404
nut exception: 1836345404
Traceback (most recent call last):
  File "nsz.py", line 99, in <module>
    nsz.compress(filePath, 18 if args.level is None else args.level, args.block, args.bs, args.output, args.threads, args.overwrite)
  File "/usr/home/media/mydev/nsz/nsz/__init__.py", line 11, in compress
    SolidCompressor.solidCompress(filePath, compressionLevel, outputDir, threads, overwrite)
  File "/usr/home/media/mydev/nsz/nsz/SolidCompressor.py", line 43, in solidCompress
    nspf.getRightsId()
  File "/usr/home/media/mydev/nsz/Fs/Ticket.py", line 171, in getRightsId
    self.seekStart(0x160)
  File "/usr/home/media/mydev/nsz/Fs/Ticket.py", line 61, in seekStart
    self.seek(0x4 + self.signatureSizes[self.signatureType] + self.signaturePadding + offset)
KeyError: 1836345404
```
I won't put keys.txt file here, but I'm using the latest one from /hbg/ discord right now.

**Comment by plato79** [comment]
The file may not be that one, I put a debug information for "could not find title key", and it was dumping like this from batch: `could not find title key 010007300DE1E800!`

The rest I already pasted up there. Though when I processed it alone it didn't write "could not find title key". So it was printing this information for the file above, though the dump is probably from another file. Although of course I couldn't see any title or file information in the dump so I cannot be sure.. I'll put a bit debug information to get exact file name.

**Comment by plato79** [comment]
Got the same dump:

```
could not find title key 010007300DE1E800!
Error when compressing file: /Switch/NSP Dumps/updates/Monaco Complete Edition[010007300DE1E800][US][v65536].nsp
1836345404
nut exception: 1836345404
Traceback (most recent call last):
  File "nsz.py", line 99, in <module>
    nsz.compress(filePath, 18 if args.level is None else args.level, args.block, args.bs, args.output, args.threads, args.overwrite, args.verify)
  File "/usr/home/media/mydev/nsz/nsz/__init__.py", line 12, in compress
    outFile = SolidCompressor.solidCompress(filePath, compressionLevel, outputDir, threads, overwrite)
  File "/usr/home/media/mydev/nsz/nsz/SolidCompressor.py", line 44, in solidCompress
    nspf.getRightsId()
  File "/usr/home/media/mydev/nsz/Fs/Ticket.py", line 171, in getRightsId
    self.seekStart(0x160)
  File "/usr/home/media/mydev/nsz/Fs/Ticket.py", line 61, in seekStart
    self.seek(0x4 + self.signatureSizes[self.signatureType] + self.signaturePadding + offset)
KeyError: 1836345404
```

**Comment by nicoboss** [comment]
That's why you shouldn't pirate games. Dump them by your own and it will work. CDN shouldn't be used for piracy especially if done wrong resulting in 010007300de1e80000000000000000010.tik contain the following content leading to the error you posted above:
```
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Please try to avoid posting issues caused by faulty dumps in the future as they are just a waste of time.

**Comment by plato79** [comment]
You're right, I should have just looked in ".tik" file first because it was about Ticket. I'll debug properly before opening an issue first.
