### ISSUE TITLE
Failed to Extract TitleID and Corrupted ncz, but finished.

### ISSUE THREAD

**Issue by ajrglkejagklje** [nicoboss/nsz#110]
The script still reports Done! at the end. Is the resulting nsp viable or should I not install it?

Failed to extract TitleID/Version from filename “FILENAME.nsz". Use -p to extract from Cnmt.

Decompressing /Downloads/FILENAME.nsz -> /Downloads/FILENAME.nsp

[ADDING] 0655aaff8fd9706842ccab67f62a42d0.nca 1445597559 bytes to NSP

Decompress 100%|██████████████████████| 6439/6439 MiB [01:40<00:00, 64.65 MiB/s]

[CORRUPTED] 0655aaff8fd9706842ccab67f62a42d0.ncz

[ADDING] 9f2ebb5aa14636edc5777ef68821c1b7.nca 152064 bytes to NSP

[CORRUPTED] 9f2ebb5aa14636edc5777ef68821c1b7.nca

[ADDING] b33ad7a90045b553ff90384544dfb0b0.nca 161792 bytes to NSP

[CORRUPTED] b33ad7a90045b553ff90384544dfb0b0.nca

[ADDING] 70b41960df6ce62a4d69aa8afbf0a505.cnmt.nca 3584 bytes to NSP

[ADDING] 70b41960df6ce62a4d69aa8afbf0a505.cnmt.xml 1440 bytes to NSP

[ADDING] 0100921006a040000000000000000003.tik 704 bytes to NSP

[ADDING] 0100921006a040000000000000000003.cert 1792 bytes to NSP

Done!

**Comment by nicoboss** [comment]
The [CORRUPTED] indicator just means that the hash of the NCA doesn't match the sha256 hash of the NCA filename. This is expected for games that where modified (either to remove game specific information as done for No-Intro dumps (yes there actually is homebrew that dumps games while removing all game/console specific information) or to actually modify something in the game like adding cheats. You can try installing it and see if it works. Just make sure that if you don't install anything from an untrustworthy source (especially if you have no eMMC backup) as there is indeed malware on the internet to brick your Nintendo Switch.

"Night in the Woods", the game you reported to be corrupted, is confirmed to properly decompress on the latest version of NSZ. So assuming you have a clean dump so this issue should be fixed on the latest [NSZ v4.1.0](https://github.com/nicoboss/nsz/releases/tag/4.2.0) release. Please let me know if you still experience this issue on the latest release.
