### ISSUE TITLE
How to use this in termux

### ISSUE THREAD

**Issue by guranu** [nicoboss/nsz#114]
How to put prod.keys to  /data/data/com.termux/files/home/.switch/
Without root?

**Comment by nicoboss** [comment]
> The keys file must be located as prod.keys file in %USERPROFILE%/.switch/(Windows)/$HOME/.switch/(UNIX) or keys.txt in the working directory.

If it's not possible for you to put prod.keys into $HOME/.switch/ because of really strange permissions just rename "prod.keys" to "keys.txt" and put it into the working directory of the nsz.py script. This is exactly why this alternative option to provide the keys exists.

**Comment by guranu** [comment]
Umm i'm talking android if this was linux i wouldn't be making this issue.
