### ISSUE TITLE
Please update PyPI version to latest

### ISSUE THREAD

**Issue by blacklein** [nicoboss/nsz#115]
Please update PyPI version to latest

**Comment by nicoboss** [comment]
Thanks a lot for reminding me. I totally agree There was no release for 2 years so I definitely should do one as the current release is basically so outdated that it makes it completely unusable. I will try to create a new release tomorrow if time allows me to do so. From the currently open issues I will try to solve https://github.com/nicoboss/nsz/issues/112 before the release but if I can’t I will release regardless.

**Comment by blacklein** [comment]
i saw some repo use Github Action workflow to make update to pypi before, but sorry i forgot which repo i saw that workflow.

**Comment by nicoboss** [comment]
The latest version 4.1.0 is now on https://pypi.org/project/nsz/ - I will do a release on GitHub soon. There is publish.cmd to automate the entire Pypi process but I still prefer doing it manually to ensure every version on Pipy is stable and well tested.

**Comment by blacklein** [comment]
I have upgrade to 4.1.0 via pypi successfully, thx a lot!
