### ISSUE TITLE
Add support for the zStandard long distance mode

### ISSUE THREAD

**Issue by paulgaijin** [nicoboss/nsz#117]
Hi. Add support for --long key from zStandard for better compression.

Also is it possible to add reverse encryption for nca? I want to compress plaintexted (decrypted) nca/nsp with rar or 7z.

**Comment by nicoboss** [comment]
Thanks a lot for your feature request. I implemented support for the zStandard long distance mode using the --long option in the latest [NSZ v4.1.0](https://github.com/nicoboss/nsz/releases/tag/4.2.0) release.

Regarding reencrypting decypted NCA files there are already a lot of tools out there that can do so. You could use the --plaintext and --ciphertext options of https://github.com/Thealexbarney/LibHac to do so. You might also be interested in my long abandoned https://github.com/nicoboss/nsZip project which allows you to LZMA compress NSP/XCI files with Dic=1536, WordS=273, cLevel=9 which is the maximum compression supported by 7zip.
