### ISSUE TITLE
Decompressed NSP files are not equivalent to original NSP source

### ISSUE THREAD

**Issue by HattDroid** [nicoboss/nsz#12]
Hi,

When decompressing an nsz, the nsp result file is different from the source nsp file.
Also these result files are not compressed by nsz.py, it produces an nsz file but about the same size as the nsp. I've noticed it's only listing nca in the output and do not execute any kind of compression and producing ncz.

file.nsp ---compress---> compressed_file.nsz ---decompress---> file_not_equal_to_src_nsp.nsp ---compress---> not_compressed_file.nsz

What kind of information could be lost in the compression or maybe decompression?
It's quite an issue to not produce nsp files that are not equivalent to the source nsp for data preservation.

On last master commit, also tried with tag 1.0.

Thanks.

**Comment by blawar** [comment]
Hello, the nsp format is not generated from nintendo.   you can’t hash the nsp to compare because packing order, packing etc all can change.  extract the nsp’s and compare the hashes of the nca’s themselves, they should match.

this is not a preservation issue since nsp is just a container format like zip, and is not copied from nintendo.

**Comment by HattDroid** [comment]
Ok, thank you for the explanation.
But how come a nsp file decompressed from an nsz cannot be compressed afterwards?

**Comment by HattDroid** [comment]
There was an issue and it seems to be solved with today's commits.
Probably this one:
https://github.com/nicoboss/nsz/commit/e94e408c5299c5534485962f91b0310d77c7f5c0

I'm currently at 076bbfc and I can convert back and forth between generated nsz/nsp files. 👍
I haven't tested installing the files on the console yet for info.

Thanks for the good work. 👍
