### ISSUE TITLE
v4.1.0 GUI doesn't work, while v4.0.1 does

### ISSUE THREAD

**Issue by Barrytoo** [nicoboss/nsz#121]
Hello,

I've been a casual user of v4.0.1 for a while, and since the release of v4.1.0, I've been trying to run it with no avail. Basically, opening nsz.py will flash a terminal windows that closes within half a second.

Since v4.0.1 still runs perfectly, and I didn't notice a change in the requirements for v4.1.0, what could I be missing?

Thanks in advance.

**Comment by nicoboss** [comment]
Can you please provide some more details like what operating system you are using and how you installed NSZ? For example, the portable version on NSZ v4.1.0 requires at least Windows 8 or newer while v4.0.1 still works on Windows 7. If you installed the Pypi version using pip or run from source please also specify your Python version.

But I guess most importantly open a terminal like CMD or PowerShell and execute nsz from there so the console window says open and you can provide the actual error message.

**Comment by Siel** [comment]
I'm having the same error
`~\Downloads\nsz_v4.1.0_win64_portable\nsz_v4.1.0_win64_portable ❯ ./nsz                                       20:26:31
Failed to import the GUI - is it installed?`
Maybe i'm missing some dependency?

**Comment by Siel** [comment]
I can also report that 4.0.1 is working

**Comment by nicoboss** [comment]
Oh I'm such an idiot. I deleted python.exe from the archive after I did all the testing.

**Comment by nicoboss** [comment]
I just released a hotfix which fixes this issue. Please replace the broken version with a fresh download of the hot-fixed "nsz_v4.1.0_win64_portable.zip" and it should work. The reason for those strange errors was because without python.exe nsz.exe tried to execute the Pypi version of NSZ instead of the portable one which either doesn't exist in the case of @Barrytoo  or has no GUI installed like in the case of @Siel. Sorry for that.

Please install https://github.com/nicoboss/nsz/releases/download/4.1.0/nsz_v4.1.0_win64_portable.zip and confirm that your problems are solved now.

**Comment by Barrytoo** [comment]
> I just released a hotfix which fixes this issue. Please replace the broken version with a fresh download of the hot-fixed [nsz_v4.1.0_win64_portable.zip](https://github.com/nicoboss/nsz/releases/download/4.1.0/nsz_v4.1.0_win64_portable.zip) and it should work. The reason for those strange errors was because without python.exe nsz.exe tried to execute the Pypi version of NSZ instead of the portable one which either doesn't exist in the case of @Barrytoo or has no GUI installed like in the case of @Siel. Sorry for that.
> 
> Please confirm if that solved the issue for you.

Well, apparently a lot has happened in my absence.

The good news is, I can confirm that it's working now. I'm surprised by the lack of reporting by other people, given that this is an issue that all will have.

I noticed that python.exe is missing from this release, and I tried copying it from the installed Python v3.10.6, but obviously didn't work.

For what it's worth, my OS is Windows 11 build 22622.590

Thanks for the quick fix.
