### ISSUE TITLE
NSP and resulting NSZ will be deleted using --rm-source when solid compression fails

### ISSUE THREAD

**Issue by Manx98** [nicoboss/nsz#124]
root@DESKTOP-4Q29HCD:~/raspbian/16TB/Switch Games/Breakout Recharged# ls
'Breakout Recharged [010022C016DC8000][v0][US].nsp'
root@DESKTOP-4Q29HCD:~/raspbian/16TB/Switch Games/Breakout Recharged# nsz -l 22 -t 6 -V --rm-source -w -C Breakout\ Recharged\ \[010022C016DC8000\]\[v0\]\[US\].nsp 
Unconfirmed: crc32(master_key_0e) = 2690905064

             NSZ v4.1   ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'

Solid compressing (level 22) /root/raspbian/16TB/Switch Games/Breakout Recharged/Breakout Recharged [010022C016DC8000][v0][US].nsp 
-> /root/raspbian/16TB/Switch Games/Breakout Recharged/Breakout Recharged [010022C016DC8000][v0][US].nsz
[ADDING]     45d101791b5e6d2b6587bc47533712c9.ncz 342736896 bytes to NSP
Compressed 53.10484634837797% 342736896 -> 182009902  - 45d101791b5e6d2b6587bc47533712c9.nca
[ADDING]     88cb85fe0e72609a1e479e6b9abbfe6f.nca 1417728 bytes to NSP
[ADDING]     8e05057667785abf2ab9d0fff78568b5.nca 175616 bytes to NSP
[ADDING]     69869906b42a183bfc4198f787992673.cnmt.nca 3584 bytes to NSP
[SKIPPED]    Content meta 69869906b42a183bfc4198f787992673.cnmt.xml
[VERIFY NSZ] /root/raspbian/16TB/Switch Games/Breakout Recharged/Breakout Recharged [010022C016DC8000][v0][US].nsz
[CORRUPTED]  45d101791b5e6d2b6587bc47533712c9.ncz
[BAD VERIFY] /root/raspbian/16TB/Switch Games/Breakout Recharged/Breakout Recharged [010022C016DC8000][v0][US].nsz
[DELETE NSZ] /root/raspbian/16TB/Switch Games/Breakout Recharged/Breakout Recharged [010022C016DC8000][v0][US].nsz

Verifying 100%|█████████████████████████████████████████████████████████████████████████████| 326/326 MiB [01:54<00:00, 2.86 MiB/s]
Deleting source file /root/raspbian/16TB/Switch Games/Breakout Recharged/Breakout Recharged [010022C016DC8000][v0][US].nsp

Done!

root@DESKTOP-4Q29HCD:~/raspbian/16TB/Switch Games/Breakout Recharged# ls
root@DESKTOP-4Q29HCD:~/raspbian/16TB/Switch Games/Breakout Recharged#

**Comment by nicoboss** [comment]
This is probably related or even a dublicate of https://github.com/nicoboss/nsz/issues/123. Something in the latest release must have gone horrible wrong. Please don’t use --rm-source until this is fixed. I will give my best to fix this as soon as possible as this is a really severe issue as it could lead to data loss.

**Comment by nicoboss** [comment]
This issue should be fixed in the latest [NSZ v4.1.0](https://github.com/nicoboss/nsz/releases/tag/4.2.0) release. Please let me know if you still experience this issue on the latest release.
