### ISSUE TITLE
Error when compressing, still.

### ISSUE THREAD

**Issue by dmnsv** [nicoboss/nsz#13]
Same file as before and now it just stops anywhere between 68-73% and the output file disappears.

nsz.py --level 22 -C "L.A. Noire - Update v1.2.nsp"
                        ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'
compressing (level 22) L.A. Noire - Update v1.2.nsp -> L.A. Noire - Update v1.2.nsz
Adding file 0100830004fb68000000000000000003.cert 1792 bytes to NSP
Adding file 0100830004fb68000000000000000003.tik 704 bytes to NSP
Adding file 4b0fe8e40b498d7a4556c3d1e8433a51.ncz 14134086144 bytes to NSP
 70%|██████████████████████████████████████████████████▊                      | 9.83G/14.1G [1:03:37<27:49, 2.58MB/s/s]

fin

nsz.py --level 22 -C "L.A. Noire - Update v1.2.nsp"
                        ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'
compressing (level 22) L.A. Noire - Update v1.2.nsp -> L.A. Noire - Update v1.2.nsz
[ADDING    ] 0100830004fb68000000000000000003.cert 1792 bytes to NSP
[ADDING    ] 0100830004fb68000000000000000003.tik 704 bytes to NSP
[ADDING    ] 4b0fe8e40b498d7a4556c3d1e8433a51.ncz 14134086144 bytes to NSP
 69%|██████████████████████████████████████████████████▎                      | 9.73G/14.1G [1:03:49<28:52, 2.54MB/s/s]

fin

Using the latest build of nsz.py. I have more than enough space free and grabbed the file from a different source, same outcome.

**Comment by nicoboss** [comment]
I just tried to compress "L A Noire" with titleid 0100830004FB6800 and version v131072 on NSZ 2.0 and everything worked perfectly fine. THe file size went from 20.5 to 9.6 GB despite using the lowest compression level possible. The NCA file names seem to match so it must be the same game and the same version. Please verify the NSP using the -V argument and try again on NSZ 2.0. I will let it run with --level 22 over night just to make sure but shouldn't even matter.

Compression output log:
[ADDING]     0100830004fb68000000000000000003.cert 1792 bytes to NSP
[ADDING]     0100830004fb68000000000000000003.tik 704 bytes to NSP
[ADDING]     4b0fe8e40b498d7a4556c3d1e8433a51.ncz 14134086144 bytes to NSP
14.1GB/s [05:55, 39.7MB/s/s]
compressed 69% 14134086144 -> 9828774629  - 4b0fe8e40b498d7a4556c3d1e8433a51.nca
[ADDING]     6f67b8afef61ef94601422e5cff63148.nca 155648 bytes to NSP
[ADDING]     b364362265b0cfbe4da7e0a559fbd7c4.nca 81920 bytes to NSP
skipping delta fragment
(...)
skipping delta fragment
[ADDING]     c221b45c0e88d33e2d238d7e3d55c340.cnmt.nca 11264 bytes to NSP
[ADDING]     c221b45c0e88d33e2d238d7e3d55c340.cnmt.xml 15532 bytes to NSP
[ADDING]     4b38a340f7fa456169c9314788b864ae.nca 198144 bytes to NSP

NSZ verification output log:
[VERIFY NSZ] .\L A Noire[0100830004FB6800][US][v131072].nsz
[EXISTS]     0100830004fb68000000000000000003.cert
[EXISTS]     0100830004fb68000000000000000003.tik
14.1GB/s [00:47, 295MB/s/s]
[VERIFIED]   4b0fe8e40b498d7a4556c3d1e8433a51.ncz
[VERIFIED]   6f67b8afef61ef94601422e5cff63148.nca
[VERIFIED]   b364362265b0cfbe4da7e0a559fbd7c4.nca
[EXISTS]     c221b45c0e88d33e2d238d7e3d55c340.cnmt.nca
[EXISTS]     c221b45c0e88d33e2d238d7e3d55c340.cnmt.xml
[VERIFIED]   4b38a340f7fa456169c9314788b864ae.nca

**Comment by dmnsv** [comment]
So I grabbed NSZ 2.0 and tried to compress the file at level 1 and it crashed with a memory error. So I enabled the page file in Windows 10 and gave myself 16GB extra and it completed. Going to retry at level 22 now.

**Comment by dmnsv** [comment]
Interesting, this is the only file I have had issues with, but I am glad I figured out a solution. I hadn't watched my RAM usage until last night and watched it climb to the point that 16GB wasn't enough so enabling the page file and giving myself 16GB of virtual memory was enough to get through the compression.

**Comment by nicoboss** [comment]
Here the object table of the memory leak happening with L.A. Noire - Update v1.2:
Created using:
```python
from pympler.tracker import SummaryTracker
tracker = SummaryTracker()
tracker.print_diff()
```
| types | # objects | total size|
|--------|:----------:|----------:|
|<class 'bytes |80958 |8.47 GB |
|<class 'dict | 106796 | 15.22 MB |
|<class 'list | 62859 | 5.47 MB |
|<class 'bytearray | 52394 | 3.65 MB |
|<class 'int | 106809 | 2.89 MB |
|<class 'Fs.Bktr.BktrSubsectionEntry | 51842 | 2.77 MB |
|<class 'method | 25990 | 1.59 MB |
|<class 'Fs.File.File | 26050 | 1.39 MB |
|<class 'nut.aes128.AESCTR | 25984 | 1.39 MB |
|<class 'Crypto.Cipher._mode_ctr.CtrMode | 25984 | 1.39 MB |
|<class 'Crypto.Util._raw_api.SmartPointer | 25984 | 1.39 MB |
|<class 'Fs.BaseFs.EncryptedSection | 25922 | 1.38 MB |
|<class 'str | 4368 | 307.19 KB |
|<class 'Fs.File.MemoryFile | 980 | 53.59 KB |
|<class 'Fs.Bktr.Bktr2 | 488 | 26.69 KB |

**Comment by 815623596** [comment]
不懂
