### ISSUE TITLE
nsz 4.3.0 nsz_v4.3.0_win64_portable won't open

### ISSUE THREAD

**Issue by jams3223** [nicoboss/nsz#133]
I downloaded the new nsz 4.3.0 version but every time i open it, it just closes automatically and doesn't work at all, i made sure to install the latest python version but it still wouldn't work but the previous version before that was working fine.

**Comment by nicoboss** [comment]
Sorry for this. I forgot to include python.exe inside nsz_v4.3.0_win64_portable.zip. Because all devices I tested this on already had Python installed and added to PATH I completely missed this during testing. I just released a hotfix patch. Please redownload nsz_v4.3.0_win64_portable.zip from the latest [NSZ v4.3.0](https://github.com/nicoboss/nsz/releases) release and let me know if everything is working for you now.

**Comment by jams3223** [comment]
OK thanks brother, i am proud of what you're doing, it's incredible for the emulation community specially the gaming one, I wanna ask you a question after i compress the xci file can they be readable when compressed like an nsz file ?

**Comment by jams3223** [comment]
Wow compression is faster even when i set it to the maximum ratio and it is slightly better compressed than before, the python application is smoother overall and perform much better than before. Congrats!

**Comment by nicoboss** [comment]
Thanks a lot for your feedback. Great to hear that everything is working for you now. I’m happy to hear that you are satisfied with the latest NSZ release.

Regarding your question: XCZ files are supported by multiple PC applications, homebrew software and title installers like Tinfoil and DBI. Keep in mind that XCZ uses block-compression by default. Block compression allows random read access directly on the compressed XCZ file without decompressing them first. For NSZ the default is solid compression which is supported by many more 3rd party software. This is just a default option that can be changed inside the settings. In the next major NSZ v5.0 release later this year I will implement a way to mount block-compressed NSZ/XCZ files as NSP/XCI to directly play them on any emulator no matter if they support NSZ/XCZ or not without decompressing them first. I hope I was able to answer your question. If you have any further questions please let me know.

**Comment by jams3223** [comment]
Wow that's a crazy idea, it will help people save a lot of space, i am happy about your work. Take care and take your time, keep on doing great things in the community.
