### ISSUE TITLE
(question) How this program unpack NSP, like the algorythm? 

### ISSUE THREAD

**Issue by YaroslavChepel** [nicoboss/nsz#142]
Ok, Im very interested in making something similar in c++. So I started to search for the unpacking algo. I saw your soft and started to see your code. Or im not so smart, or just lazy, but I want to hear an algorythm.
Like how did you write this unpacker?

**Comment by blawar** [comment]
https://switchbrew.org/wiki/NCA#PFS0

The NSP is just a PFS0 filesystem.  The structure is described on that site.

Ignore the first table, it is only used when PFS0 is embedded in a NCA.  You want the second and third tables.
