### ISSUE TITLE
Question about sections

### ISSUE THREAD

**Issue by duckbill007** [nicoboss/nsz#15]
It is not clear from description: does sections covers all file (0x4000-EOF) or only describes parts of the file that should be reencrypted.

Also, how can I get uncompressed length? Should I get it from original nca header, or I can get it from last section offset+length?

**Comment by nicoboss** [comment]
When using solid compressen everything from 0x4000 to EOF is compressed as one pice. Block compression compresses the exact same region just in individual compressed chunks to allow random read access.
Every NCA contains something similar to partitions called sections covering everything from 0x4000 to EOF. They use different encryptions and so have individual NCZSECTN headers to make encrypting them as easy as possible. You can just calculate 0x4000 + the size of all sections or calculate offset of last section + size of last section to get the decompressed NCA size.
If you have any further questions or need any help implementing the NSZ file format feel free to ask.
