### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by dvlasoff** [nicoboss/nsz#162]
Here is the output:

[INFO   ] [Logger      ] Record log in C:\Users\danie\.kivy\logs\kivy_23-12-08_3.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.6.0
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "D:\WIP\nsz_v4.5.0_win64_portable\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 546.29'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[WARNING] [Deprecated  ] Deprecated in 2.1.0, use on_drop_file event instead. Event on_dropfile will be removed in the next two releases.: Call to deprecated function on_dropfile in D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\kivy\core\window\__init__.py line 2143.Called from D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\kivy\core\window\__init__.py line 1076 by <lambda>().
[INFO   ] [Base        ] Leaving application in progress...

             NSZ v4.5   ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'

master_key_10 missing from C:\Users\danie\.switch\prod.keys! This will lead to corrupted output.
master_key_10 missing from C:\Users\danie\.switch\prod.keys! This will lead to corrupted output.
master_key_10 missing from C:\Users\danie\.switch\prod.keys! This will lead to corrupted output.
master_key_10 missing from C:\Users\danie\.switch\prod.keys! This will lead to corrupted output.
Solid compressing (level 18) D:\WIP\NSP\CENSOREDTITLE.nsp -> D:\WIP\NSP\CENSOREDTITLE.nsz
[ADDING]     01003dc0144b68000000000000000011.cert 1792 bytes to NSP
[ADDING]     01003dc0144b68000000000000000011.tik 704 bytes to NSP
[ADDING]     2856182e3e036a2009ca2609727b0172.nca 1234432 bytes to NSP
[ADDING]     5bea037c53cbf4a6d5a5ae27859f0793.nca 175104 bytes to NSP
Traceback (most recent call last):
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\nsz\SolidCompressor.py", line 133, in solidCompressNsp
    processContainer(container, nsp, compressionLevel, keepDelta, useLongDistanceMode, threads, statusReport, id, pleaseNoPrint)
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\nsz\SolidCompressor.py", line 29, in processContainer
    offsetFirstSection = sortedFs(nspf)[0].offset
IndexError: list index out of range

[VERIFY NSZ] D:\WIP\NSP\CENSOREDTITLE.nsz
nut exception: [Errno 2] No such file or directory: 'D:\\WIP\\NSP\\CENSOREDTITLE.nsz'
Process Process-2:
Traceback (most recent call last):
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\nsz\__init__.py", line 40, in solidCompressTask
    verify(outFile, removePadding, True, keepDelta, None if quickVerify else filePath, [statusReport, id], pleaseNoPrint)
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\nsz\__init__.py", line 70, in verify
    NszVerify(filePath, removePadding, raiseVerificationException, raisePfs0Exception, originalFilePath, statusReportInfo, pleaseNoPrint)
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\nsz\NszDecompressor.py", line 46, in verify
    __decompressNsz(filePath, None, removePadding, False, raiseVerificationException, raisePfs0Exception, originalFilePath, statusReportInfo, pleaseNoPrint)
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\nsz\NszDecompressor.py", line 191, in __decompressNsz
    fileHashes = FileExistingChecks.ExtractHashes(filePath)
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\nsz\FileExistingChecks.py", line 14, in ExtractHashes
    container.open(str(gamePath), 'rb')
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\nsz\Fs\Nsp.py", line 198, in open
    super(Nsp, self).open(path or self.path, mode, cryptoType, cryptoKey, cryptoCounter)
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\nsz\Fs\Pfs0.py", line 204, in open
    r = super(Pfs0, self).open(path, mode, cryptoType, cryptoKey, cryptoCounter)
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\nsz\Fs\BaseFs.py", line 97, in open
    r = super(BaseFs, self).open(path, mode, cryptoType, cryptoKey, cryptoCounter)
  File "D:\WIP\nsz_v4.5.0_win64_portable\lib\site-packages\nsz\Fs\File.py", line 210, in open
    self.f = open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\WIP\\NSP\\CENSOREDTITLE.nsz'

**Comment by Masamune3210** [comment]
Btw, censoring the title doesn't really work when you leave the titleID uncensored lol
