### ISSUE TITLE
[Fixed in NSZ 4.6.1] MPLUS1p-Medium.ttf not found in NSZ 4.6.0

### ISSUE THREAD

**Issue by RinMaru** [nicoboss/nsz#164]
Microsoft Windows [Version 10.0.22635.2915]
(c) Microsoft Corporation. All rights reserved.

Z:\Yuzu\user\games\nsz_v4.6.0>nsz.exe
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.6.0
[INFO   ] [Kivy        ] v2.2.1
[INFO   ] [Kivy        ] Installed at "Z:\Yuzu\user\games\nsz_v4.6.0\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "Z:\Yuzu\user\games\nsz_v4.6.0\python.exe"
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
nut exception: File Z:\Yuzu\user\games\NSCB_101bx64\nsz_v4.1.0\Lib\site-packages\nsz\gui\fonts\MPLUS1p-Medium.ttf not found
 Traceback (most recent call last):
   File "Z:\Yuzu\user\games\nsz_v4.6.0\lib\runpy.py", line 196, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File "Z:\Yuzu\user\games\nsz_v4.6.0\lib\runpy.py", line 86, in _run_code
     exec(code, run_globals)
   File "Z:\Yuzu\user\games\nsz_v4.6.0\nsz.exe\__main__.py", line 7, in <module>
   File "Z:\Yuzu\user\games\nsz_v4.6.0\lib\site-packages\nsz\__init__.py", line 93, in main
     from nsz.gui.NSZ_GUI import GUI
   File "Z:\Yuzu\user\games\nsz_v4.6.0\lib\site-packages\nsz\gui\NSZ_GUI.py", line 3, in <module>
     from kivy.core.text import LabelBase, DEFAULT_FONT
   File "Z:\Yuzu\user\games\nsz_v4.6.0\lib\site-packages\kivy\core\text\__init__.py", line 1077, in <module>
     Label.register(DEFAULT_FONT, *_default_font_paths)
   File "Z:\Yuzu\user\games\nsz_v4.6.0\lib\site-packages\kivy\core\text\__init__.py", line 365, in register
     raise IOError('File {0} not found'.format(font_type))
 OSError: File Z:\Yuzu\user\games\NSCB_101bx64\nsz_v4.1.0\Lib\site-packages\nsz\gui\fonts\MPLUS1p-Medium.ttf not found

Z:\Yuzu\user\games\nsz_v4.6.0>

Im getting this error and the program refuses to start

**Comment by nicoboss** [comment]
Thanks a lot for reporting this. You are affected by #154. #154 got fixed in NSZ 4.6. This unfortunately had the side-effect that NSZ 4.6 doesn't start for everyone who got affected by this issue in previous versions. A new NSZ version will be deployed later today which will automatically detect and fix this issue.

Please delete the following file to get NSZ 4.6.0 GUI working:
**Windows:** C:\Users\<UserName>\.kivy\config.ini
**Linus:** /home/<UserName>/.kivy/config.ini
**macOS:** /Users/<UserName>/.kivy/config.ini

**Comment by nicoboss** [comment]
A fix for this issue got implemented in the latest [NSZ 4.6.1](https://github.com/nicoboss/nsz/releases) release! NSZ 4.6.1 automatically repairs the Kivy configurations. It does so by resetting the default_font property if corrupted.

I will close this issue in around a day once everyone should be aware of the NSZ 4.6.1 release
