### ISSUE TITLE
Enhanced File Existing Check

### ISSUE THREAD

**Issue by nicoboss** [nicoboss/nsz#20]
Let’s implement a function returning string(titleid) and int(version) from any NSP/NSZ file path.
If that data can be found in the filename it will be obtained using regex, if not the files metadata will be phrased.

Inside nsz.py:
Let's create a dictionary of all filenames in the destination folder.
Let's also create a dictionary containing dict(titleid, dict(version, filename))

Inside FileExistingChecks.py:
1. Let's obtain titled and version from the current file we want to check
2. If --rm-old-version is enabled let's delete all older versions of it and remove the deleted files from booth dictionaries
3. let's check if a file with the same version and titleid already exists.
    - If --overwrite is enabled let's delete it and remove the deleted files from booth dictionaries
3. If there's still a file with the exact same filename inside the filelist dictionary
    - If --overwrite is enabled let's delete it and remove the deleted files from booth dictionaries
    - Otherwise let's skip the compression and notify the user.

**Comment by gut5** [comment]
BTW there is a bug in the commit from a few minutes ago

`                        ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'
nut exception: exceptions must derive from BaseException
Traceback (most recent call last):
  File "./nsz.py", line 102, in <module>
    targetDict = FileExistingChecks.CreateTargetDict(outfolder, ".nsz")
  File "/home/guts/nx/nsz-master/nsz/FileExistingChecks.py", line 52, in CreateTargetDict
    IdVersion = ExtractTitleIDAndVersion(file)
  File "/home/guts/nx/nsz-master/nsz/FileExistingChecks.py", line 42, in ExtractTitleIDAndVersion
    raise("Failed to determinate TitleID/Version!")
TypeError: exceptions must derive from BaseException

`

**Comment by nicoboss** [comment]
Thanks for reporting it. I wasn't able to find any game throwing an "Failed to determinate TitleID/Version!" exception so far. Please run it again on latest commit so you can see which game causes that error and report it so I can recreate and fix it. Generally, always expect bugs when using latest commit instead of latest stable version. Commits are barely tested and I'm often directly working in the master branch and plan doing so at least until all important features are implemented.

**Comment by gut5** [comment]
No problem man, I do generally expect that with anything other than stable builds on Github.
I noticed the specific bug I reported was only happening with games without a titleid in the filename. I haven't tried the new version yet but I'll do it in a little while and report back.

**Comment by gut5** [comment]
Found what could be considered a bug with this. If you start a long convert with the latest version which includes this functionality, and then you open a different terminal and run the script on a nsp in the same folder, it picks up the file already being converted and throws a "but exception: Not a valid PFS0 partition b'\x00\x00\x00\x00' error.

I guess you could work around this by having multiple operating folders to run the script but obviously this isn't ideal.

**Comment by gut5** [comment]
Also looks like my suspicion about files not having the titleid in the  filename causing a broken file to be produced was unfounded, I just tested the latest version with file with no titleid in filename and it works fine.
