### ISSUE TITLE
XCZ support

### ISSUE THREAD

**Issue by popy2k14** [nicoboss/nsz#23]
Is XCZ support planned?

**Comment by nicoboss** [comment]
XCZ support is planned for the near future. XCZ will use block compression by default allowing them to be mounted and played without installing on Emulators/Real hardware (once supported by any homebrew). The only missing piece for XCZ support is a Hfs0Stream similar to Pfs0Stream required to build the actual XCI container. NSC_BUILDER already supports XCZ however only solid compressed and so shouldn't be used.

**Comment by popy2k14** [comment]
thx, for clearing things up.

**Comment by nicoboss** [comment]
Thanks to blawar XCZ support was finally added. Block compression is used by default as XCI is known to be the mountable format but solid XCZ compression is supported. too. XCZ support is considered stable and will be in the next nsz v3.0 release which will be released in the next few days.

**Comment by popy2k14** [comment]
Thx a lot for your and blawar's efforts, will try this after it has been released.
