### ISSUE TITLE
Endless decompression/verification on a few block compressed games

### ISSUE THREAD

**Issue by nicoboss** [nicoboss/nsz#25]
Some block compressed games infinitely decompresses/verify.

How to reproduce: Block compress Noire_0100830004FB6800_[v131072] and then just decompress it. After the process bar finishes it will be just stuck while still doing something in the background what never seems to end. This issue was first reported on https://gbatemp.net/threads/ryjin-a-nsz-converter-mod.550174/page-7 by GnK23 using a 500 MB game and so definitely something else then Noire. Unlike GnK23 I was able to reproduce this issue in booth 2.0 and latest commit.

If you noticed any other game affected by this issue please let me know.

**Comment by AustinHasten** [comment]
Currently experiencing this with [0100C4E004406800][US][v262144].

**Comment by nicoboss** [comment]
Big thanks to blawar for fixing this issue inside https://github.com/nicoboss/nsz/commit/d03a51801035233ae3bb481669e58bfda3b03c65
