### ISSUE TITLE
TQDM progress report for compression is incorrect

### ISSUE THREAD

**Issue by eXhumer** [nicoboss/nsz#31]
Sometimes, the progress bar shows 100%, but still keeps processing in the background. I believe it has something to do with TQDM incorrectly reporting the size processed. Though I haven't looked into the code. Will provide video when I compress my next NSPs to show bug in action.

**Comment by eXhumer** [comment]
On second thought, it looks like it has something to do with level instead.

**Comment by nicoboss** [comment]
When using solid compression with multiple threads zStandard is progressing data very wired and so even completely independent nsz tools have the same issue: https://github.com/julesontheroad/NSC_BUILDER/issues/83
It's really ugly but luckily doesn't affect the resulting file in any way. I will see what I can do about it - probably while implementing GUI.

**Comment by eXhumer** [comment]
https://github.com/tqdm/tqdm/blob/master/.meta/.readme.rst

I think the example provided here can fix it, I'll see if I can figure out how to implement it in the script.

**Comment by eXhumer** [comment]
Decompressor TQDM was fixed in #33.

Looking into compressor soon.

**Comment by nicoboss** [comment]
With the implementation of the multithreaded multiple process bars communication system using enlighten this issue got finally fixed.
