### ISSUE TITLE
Progress bar halts at 15% 

### ISSUE THREAD

**Issue by Trunkzeh** [nicoboss/nsz#32]
macOS Catalina
Python environment 3.7.3 via pyenv
Installed nsz via pip container (current version 2.1)

"nsz -C -l 22 -t 3 Game.nsp"

<img width="1058" alt="Screenshot 2019-11-14 at 14 15 41" src="https://user-images.githubusercontent.com/52528608/68864566-44d24900-06e9-11ea-9aae-3609fdf5547e.png">

I've tried this with multiple NSP files. One thing to denote that these NSP files were once XCI dumps converted using 4nxci. They all work as they are currently installed on my Switch SD card.

**Comment by nicoboss** [comment]
Please try with only one thread and see if the same issue still occurs. The progress bar of multithreaded solid compression is visually broken as already reported in #31
This is only a visual bug so as long it's using CPU and the output file grows it’s working. Wait around 1 hour and see if it complete – level 22 is very slow.
The pip package is only a few hours old so this could also be a completely new bug as I never tested it with such huge games.

**Comment by Trunkzeh** [comment]
Yes python is running at 100% however the progress bar halts. I did have a
look at #31 but wasnt sure it pertained to my issue. I'll feedback after an
hour or so.

**Comment by Trunkzeh** [comment]
@nicoboss Just feeding back - this works correctly. Took about 40minutes to do a 14gb nsp on level 22 (shaved around 4gb off the original size!) Its just a progress bar issue which i guess is what issue #31 is about. Is it possible for nsz to run through an entire directory instead of specifying one file at a time? Perhaps a future feature request 👍

**Comment by nicoboss** [comment]
Great to hear! Just specify a folder path instead of a file and it will progress all the files in that folder:
nsz -C -l 22 -t 3 Folder.nsp
By the way in case you want to use block compression enter "pip install nsz --upgrade" as in your current version that's broken.
