### ISSUE TITLE
" use nsz like every other cmd command or just use the windows portable build."

### ISSUE THREAD

**Issue by porridge2215** [nicoboss/nsz#36]
i have:
-    nsz-2.1.1 unrared as a folder in c:\nsw\NSZ
-    prod key in the right place
-    latest python installed,
-    running from a windows 10 cmd (admin) console
-    the console is in e.g. C:\NSW\NSZ

but "pip install nsz" gives LOTs of red lines: eg
```
Collecting nsz
  Using cached https://files.pythonhosted.org/packages/14/23/0eb200d2052203e94ffc311829b4df82db43e6660cb0f4ca7fedbcdba4d0/nsz-2.1.1-py3-none-any.whl
Collecting colorama
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting pycryptodome==3.9.0
  Using cached https://files.pythonhosted.org/packages/b6/41/d3749c0caa860041eb6b0832c7087253d59cb5af8bb303a8d4b6daa74014/pycryptodome-3.9.0.tar.gz
    ERROR: Command errored out with exit status 1:

```
**it also says "or just use the windows portable build."
havent a clue where this is... is it an exe?**

sorry to use this as a forum to help, discord was a waste of time...

**Comment by nicoboss** [comment]
No problem. Feel free to always create a issue if you need any help with nsz.

You can find the standalone portable windows executable build under https://github.com/nicoboss/nsz/releases - the latest one is https://github.com/nicoboss/nsz/releases/download/2.1.1/nsz_v2.1.1_win64_portable.zip

pip shouldn't fail. I just experienced the exact same issue inside a clean VM and will investigate why this happens. Maybe Python 3.8 is just too new for pycryptodome v3.9.0 as the latest pycryptodome version works perfectly fine. Using Python 3.7 instead should fix your issue. I will see what I can do about it.
