### ISSUE TITLE
Decompressing NCZs

### ISSUE THREAD

**Issue by JupiterJesus** [nicoboss/nsz#38]
When I try to pass in the name of an NCZ file (after separately extracting all files within the NSZ with a different tool), the app finishes instantly and does nothing. I assume that decompressing individual NCZ files is not implemented, is that correct?

If this is intended behavior (or an oversight), then consider this a feature request. I really want this functionality, and it seems like it would be really quick to implement.

NSZ works just fine if I want to extract and repack the entire .nsz file, but doing it like this would require some significant changes to the custom tools and code I'm already using. Decompressing a single NCZ, however, was a relatively simple thing to insert into my existing toolchain, and I'd hoped that your tool would do it.

If this is already possible, please let me know how. Currently, passing in an NCZ file with the following command line does nothing:
`
./nsz -D --output 'extracted\Nsz\Dir' 'extracted\Nsz\
Dir\fc255efbda053ecf0ccc1f071a4f9e86.ncz'
`
This is the only output, and no file:

> 
>            NSZ v2.1.1   ,;:;;,
>                        ;;;;;
>                .=',    ;:;;:,
>               /_', "=. ';:;:;
>               @=:__,  \,;:;:'
>                 _(\.=  ;:;;'
>                `"_(  _/="`
>                 `"'
> 
> Done!

**Comment by JupiterJesus** [comment]
FYI, my current workaround is to fully decompress the NSP file using your tool BEFORE my tools go in and take apart the decompressed NSP as normal. It's definitely an inefficient way to do it since there's typically only one compressed NCA in there, but for me, processor cycles are cheap and my free time to code is precious :)

**Comment by nicoboss** [comment]
There is IndependentNczDecompressor.py inside the nsz project. It's a completely independent script you can use to decompress NCZ files. Use it like "python .\IndependentNczDecompressor.py .\in.ncz out.nca".  IndependentNczDecompressor is poorly maintained and based on the original decompression approach so better sha256 verify the NCAs produced that way. 

Adding NCZ decompression support to nsz should be very easy and that way NCZ decompression will use the same decompressor as everything else. I will try to finish implementing that today so it can make it into the NSZ v3.0 release which will be released later today or tomorrow.

By the way you don’t have to use any 3rd party tool to extract NSP/NSZ files. Just use “python nsz.py -x .\YourGame.nsz”
