### ISSUE TITLE
Verify compressed nsz files with the gui will crash the gui without error or warning or log 3.0 h1

### ISSUE THREAD

**Issue by skygunner** [nicoboss/nsz#44]
Reproduce:
nsz_v3.0.0_hotfix1_win64_portable.zip
add gen10 prod.keys
load two .nsz files via select/load nsz files
click verify
the Gui crashed and closed. 

System Windows 10 64B, Python 3.8

**Comment by nicoboss** [comment]
Thanks for reporting. This issue was fixed in https://github.com/nicoboss/nsz/commit/c484887f732365874b7bb549e689f2f49b130d8b and it's fix made it into todays nsz 3.1 release: https://github.com/nicoboss/nsz/releases/tag/3.1.0
