### ISSUE TITLE
master_key_09 missing from keys.txt

### ISSUE THREAD

**Issue by popy2k14** [nicoboss/nsz#45]
Hey guys.

Thx a lot again for adding xcz support.
Would like to compress my backups and got the following error:

> master_key_09 missing from keys.txt
> Traceback (most recent call last):
>   File "nsz\nut\Keys.py", line 107, in load
> OSError: master_key_09 missing from keys.txt

> master_key_09 missing from keys.txt
> Compressing  13%|████████                                                      |  377/2953 MiB [00:42<04:47, > 8.97 MiB/s]

But the compression is going on (percentage is increasing)?

Do i have to get my keys.txt again?
Any hints?

thx a lot

**Comment by nicoboss** [comment]
Having missing keys is never a good sign and should be avoided whenever possible. As long the game can be played on your current firmware and you dumped its keys you should be fine but generally such an error means it can't decrypt something leading to some or all data being stored uncompressed. As long verification is successful and you are satisfied with the compression ratio you achieved it's fine as it was able to compress the main game but I highly recommend updating to latest firmware and dumping the latest keys using https://github.com/shchmue/Lockpick_RCM/releases

To ensure this isn't a bug please go check your keys.txt or prod.keys and see if master_key_09 is really missing. I can confirm that I definitely have master_key_09 inside my prod.keys.

**Comment by popy2k14** [comment]
I dont have an master_key_09 in my keys.txt (dumped again and rechecked).
The latest is master_key_08.
I am on 8.1.0 FW and the issue pops up on an relative old title "Kirby Star Allies".
Can play it without an issue.
Why is the 09 key needed?

Should i'll upgrade to the newest FW to get the 09 key and try again?

thx

**Comment by popy2k14** [comment]
I have solved the issue.
I had to update sept so Lockpick_RCM could generate/extract the newer keys.
No need to upgrade to newer firmware.
Now the issue s gone. Closing the issue now.
Maybe this will help someone else.

thx
