### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by xxwiredxx** [nicoboss/nsz#53]
Unhandled exception at 0x00007FF965CA092A (python38.dll) in python.exe: 0xC0000005: Access violation reading location 0x000000000000000B. occurred

It seems as if it cannot find python38.pdb

I have installed Python 3.8.* and Visual studio

This is happening when installing nsz and also running the requirements.txt

Windows 10 - I do python coding and others

**Comment by xxwiredxx** [comment]
This was created trying to use Python 8+, I corrected the issue downgrading.

**Comment by nicoboss** [comment]
This issue seems to be fixed with latest NSZ v4.0 release please reopen it you can still recreate it on that version.
