### ISSUE TITLE
Fails to compress DLCs with key_area_key_application_0a

### ISSUE THREAD

**Issue by eXhumer** [nicoboss/nsz#54]
Latest DLCs with key_area_key_application_0a fails to compress with the latest release (not sure about master) of nsz.
If you need a DLC with key_area_key_application_0a, contact me on Discord. (knightslayer#9443)

**Comment by eXhumer** [comment]
UPDATE: Problem is with the Keys.py file and blawar already has a fix for it.

**Comment by nicoboss** [comment]
This was fixed in master 27 days ago and should be in the next release which will be during the next 2 weeks: https://github.com/nicoboss/nsz/commit/db10e4eca2a3e3ad7ff47b56616b4f812792e035
