### ISSUE TITLE
gdrive and roms

### ISSUE THREAD

**Issue by daveftw84** [nicoboss/nsz#55]
im trying to get my gdrive to mount with tinfoil. so far i can only open my gdrive with nutfs.
when adding gdrive to file browser, its empty. i have no path set. 
when using nutfs. i added the nutfs path of my roms (nutfs://192.111.1.11:9000/gdrive/mydrive/roms)
inside the roms folder is a snes folder and inside the snes folder is roms, stored in zips.
do i have to extract all the rom zips to get tinfoil to scan them in?

**Comment by nicoboss** [comment]
What does this have to do with the nsz file format? I and the NSZ project is not related to tinfoil or any other homebrew using the NSZ file format in any way. Please contact the homebrews author if you experience any issues with such tools. The NSZ also is only a format to compress Nintendo Switch game and doesn't have anything to do with games for other consoles like SNES. The .nsz files have nothing to do with .zip files - they booth technically completely different. Please also keep in mind that the NSZ project has a zero tolerance for piracy even for SNES games.
