### ISSUE TITLE
ncz decompression is not working

### ISSUE THREAD

**Issue by drmeerkat** [nicoboss/nsz#59]
Hi nicoboss,

Thanks for your great work. I am trying to decompress the 1.1.1 updates for ACNH. It contains ncz file and I cannot use `nsz -D filename.ncz` to decompress.

`Summary of errors which occurred while processing files:
Error while processing /Users/drmeerkat/Downloads/switch/games/Animal Crossing New Horizons[01006F8002326800][US][v131072][CR-18]/3119652241e80b83078c27a3abb79d2e.ncz
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.7/site-packages/nsz/__init__.py", line 218, in main
    if not args.overwrite and outfile.is_file():
AttributeError: 'str' object has no attribute 'is_file'`

Then I manually fix this by removing the file existing check from __init__.py. But now another bug comes,
`
Summary of errors which occurred while processing files:
Error while processing /Users/drmeerkat/Downloads/switch/games/Animal Crossing New Horizons[01006F8002326800][US][v131072][CR-18]/3119652241e80b83078c27a3abb79d2e.ncz
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.7/site-packages/nsz/__init__.py", line 222, in main
    decompress(filePath, outfolder)
  File "/Applications/anaconda3/lib/python3.7/site-packages/nsz/__init__.py", line 64, in decompress
    NszDecompress(filePath, outputDir, statusReportInfo)
  File "/Applications/anaconda3/lib/python3.7/site-packages/nsz/NszDecompressor.py", line 21, in decompress
    container.open(filePath, 'rb')
  File "/Applications/anaconda3/lib/python3.7/site-packages/nsz/Fs/File.py", line 222, in open
    raise IOError('Invalid file parameter')
OSError: Invalid file parameter
`

Could you help with this?

**Comment by nicoboss** [comment]
Thanks a lot for reporting that issue. The built in NCZ decompression was poorly tested and had indeed some bugs. People usually just use `.\nsz\IndependentNczDecompressor.py in.ncz out.nca` to decompress Ncz files which works perfectly fine and so the nobody ever noticed that the built in one introduced in nsz v3.0.0 was never working properly. Sorry that it took so long for me to answer. I was busy with University and so didn't had time to investigate and fix this until now.

**Comment by drmeerkat** [comment]
Thank you Nico!

Nico Bosshard <notifications@github.com> 于2020年4月10日周五 下午10:43写道：
