### ISSUE TITLE
unrecognized arguments : -t or --threads

### ISSUE THREAD

**Issue by liamkesatoran** [nicoboss/nsz#6]
Readme says that -t or --threads can be used as an optional arguments but I get the error that they are unrecognitzed. 

There is also no parser.add_argument('-t','--thread',       ............) line in nsz.py or any multithread argument in nut.compress

Cheers and thanks for the awesome work.

**Comment by blawar** [comment]
It was removed since it barely helped speeds and hurt compression ratio.
