### ISSUE TITLE
A little functional suggestion for GUI

### ISSUE THREAD

**Issue by ches1y** [nicoboss/nsz#61]
1. "Output Folder" should go Settings. And set input folder as output folder by default.
2. Kivy settings add "font" function, right now nsz_gui cant display Non-English characters well.

Thanks!

**Comment by nicoboss** [comment]
Thanks a lot for your feedback. I implemented all requested changes in a way I considered the best for the project.

I changed it so the parent folder of each input file is now the default output folder. This was kind of hard to implement as now there can be multiple output folders all having to support options like override and rm-old-version which require all files in that directory to be analyzed and its information cached before writing to the but luckily it wasn't as hard as first though. I kept the button to select the output folder on the main window for now as it's a heavily used feature but you can just ignore it if you are satisfied with the default options. In the future I might save the last output folder just so the user can faster select it if he wants it over the default behavior but that won't be part of the upcoming NSZ v3.2.1 release.

I changed the default font to "M+ 1p" as a good looking Japanese focused multi-language open source font with 8,676 glyphs and 42 supported languages according to fontdrop.info plus Japanese, partial Chinese and probably more it hasn't detected. I didn't make it officially changeable as different fonts often require some GUI tuning to look good however if you really want to change it you now can by replacing "MPLUS1p-Medium.ttf" with whatever font you like.

With this I'm now closing this issue however feel free to give additional feedback (either here or in a new issue) especially if you disagree with how I implemented the requested futures.
