### ISSUE TITLE
Use this tool - imposSiBrU!11 (ノP_ P)ノ彡┻━┻

### ISSUE THREAD

**Issue by FranciskRae** [nicoboss/nsz#74]
Hi, I'm just a player who wants to unpack one game from nsz to nsp.
I am not a programmer, but an experienced PC user who knows how to use the command line and do anything on the guides ;)
I hope that I am writing in the right place, and my message here will not interfere with anyone.
(I write using Google translation)
So, by the way, recently I also installed CEMU and one game on it, and still have difficulties unpacking game archives, and I also need a key file, and all this is not new to me, in General, I like to play unique games through emulators. This I to what there I with this was able cope with all actions for couple of hours, and here trying to unpack game for Yuzu I already sit the entire day and nor as not can achieve outcome.
At first I tried to use the portable version for Windows, but after the launch it would open the command-line window for a second and close.
Then I tried using sourcecode by downloading a portable Python interpreter , but no matter how I tried to run it nsz.py , nor what did not work although run on the command line "Python nsz.py" and specifying the full paths both to the Python executable and to nsz.py I don't know where to look at any logs either, although I've been reading about it all day.
Unfortunately, the tool does not have any simple step-by-step guide for the simple users for whom this tool would seem to be created.
Then, reading again and again, I realized that the portable version for Windows does not start due to a lack of keys.txt
And here I remember that by the way I wrote above, about a similar program but for games on CEMU, in that program, you also need keys to work, but there the program clearly says this by displaying an information plate at the beginning of the launch
In General, I provided the key file to the program, it started, I tried to unpack the nsz I needed
but after the start, the program started to work in the console window, and then closed, unpacking never happened.
then I noticed that in the same console window, the program reports that some keys are missing in the key file, for new firmware versions
Provided the program with the most complete key file with all the necessary and now the program in the console window has stopped writing about the lack of some keys
I try to unpack the nsz I need again, but the program still closes without unpacking nsz.
The only log file that I can find is the log mentioned in the console window of the program, as I understand it is the GUI log, it says that some modules are missing(which are not initially in the program directory) and one. dll which is also just not there initially.
[kivy_20-05-24_8.txt](https://github.com/nicoboss/nsz/files/4674310/kivy_20-05-24_8.txt)
And then I do not understand, I do not have enough simple clear and accessible information, I have to download these files from some other project, they are not available for compliance with copyrights, or they just forgot to include them in a portable package?
I just used to understand a portable package as it is accepted, by the fact that the program does not require the usual installation and works just after unpacking from the archive, so it usually also carries with it in a set of all-necessary redistributions and other related libraries for Autonomous operation.
And here it was not so, I expected that I would download a simple little tool that will do its job in 5 minutes, and now it has been 12 hours and wain is still there ;)
Help me understand how to use this tool as easily as possible without installing interpreters and SDK, just using the command line to specify which file to unpack and that's it.

**Comment by nicoboss** [comment]
Sorry for all the troubles you had with my tool. Next time feel free to ask way earlier if you have any issues.

As clearly stated in the readme and the error message either a prod.keys file at %USERPROFILE%/.switch/ or keys.txt in the same folder as your working directory is required for this tool to work as it would be illegal to share such keys. Every major firmware update uses a new masterkey and so requires more keys in that file to successfully decrypt the game.

I never seen above posted error before. Seems to be GUI related. Just use the tool command line only and it shouldn't appear.

To decompress a folder full of your compressed games:
```
.\nsz.exe -D C:/path/to/folder/with/compressed/games/
```

If you want fast help send me your Discord username and we can live chat there.

**Comment by FranciskRae** [comment]
![1](https://user-images.githubusercontent.com/65868712/82765189-1e6e3280-9e1d-11ea-9409-cee38bad3f3a.jpg)
the same problem, the same files are missing, as was written in the Kivy log

**Comment by nicoboss** [comment]
Never heard on anybody missing ANSI64.dll as it's part of Windows. At least part of Windows 10. I will test on Windows 7 VM soon. In the meantime, try if https://github.com/nicoboss/nsz/releases/download/2.1.1/nsz_v2.1.1_win64_portable.zip works for you as this DLL shouldn't be required for NSZ v2.1.1.

**Comment by FranciskRae** [comment]
It's Working. Hurray! It's alive!;)
Now I'll tell you everything..
I'll just translate it now

**Comment by nicoboss** [comment]
Awesome you finally got my tool working! Thanks a lot for all your testing. I highly appreciate the time you put into writing all this.

I just created a clean Windows 7 x64 Ultimate virtual machine and can confirm that I'm getting that missing ansi64.dll error there too. Thanks a lot for reporting that as I never tested NSZ v3.1.1 on Windows 7 and without your feedback I might never would have fixed that error.

It turned out that every Windows operating system prior to Windows 10 v1511 from November 10, 2015 lacked ANSI support and so ANSICON using the ansi64.dll is required in order to display non-ASCII characters to the CMD window. Sorry for all that troubles caused by me forgetting to add that DLL file for legacy operating systems.

It isn't my fault that %USERPROFILE%/.switch/prod.keys is the default key path that almost every tool uses. The folder name ".switch" has to do with Linux where the dot prefix marks a folders as hidden. In Windows you can easily create such folders by just naming them ".switch." (with a dot as suffix and prefix) unfortunately some user don't know that which is why my tool also except the less standardized keys.txt file which works equivalently.

**Comment by FranciskRae** [comment]
> In Windows you can easily create such folders by just naming them ".switch." (with a dot as suffix and prefix) unfortunately some user don't know that which is why my tool also accepts the less standardized keys.txt file which works equivalently.

wow, I didn't know that, I checked and it works, thank you. "century live - century learn"

> I also saw that issue with the window closing immediately on the portable version and so making it impossible to see the missing key error. I will fix that in the next version too.

Thank you for your attention to the problem.

I will make sure to check for a new version if I need to unpack nsz again ;)

**Comment by nicoboss** [comment]
Thanks a lot for all your feedback. With today’s NSZ v4.0 release every Windows Version from Windows Vesta to latest Windows 10 including Windows 7 is now supported. I also highly improved the missing prod.keys/keys.txt error message and it now waits for the user to press Enter before exiting. When starting NSZ with GUI it now always asks the user to press enter before exiting so the content on the console including potential errors can be seen.
