### ISSUE TITLE
Console says master_key_07 missing from keys.txt

### ISSUE THREAD

**Issue by denkeel** [nicoboss/nsz#76]
Traceback (most recent call last):
  File "nsz\nut\Keys.py", line 107, in load
OSError: master_key_07 missing from keys.txt

master_key_07 missing from keys.txt
Done!

**Comment by denkeel** [comment]
I'm trying to decompress nsz, but error trows up. pls help

**Comment by deadair3210** [comment]
I mean, if it says that you are missing master_key_07, have you checked to see if you are missing it ?

**Comment by denkeel** [comment]
Yes, it is missing. But that what these are correct keys

**Comment by denkeel** [comment]
I don’t think there should be key_7

**Comment by deadair3210** [comment]
There are as of the last few updates 10 master keys. You need whichever one your game requires, or more likely it's just easier to update your switch to the latest firmware and extract the keys yourself

**Comment by denkeel** [comment]
Year thanks. The keys were the problem. And it wasn't an error, it was just a warning.
