### ISSUE TITLE
Last block that cannot be compressed cannot be decompressed

### ISSUE THREAD

**Issue by gabest11** [nicoboss/nsz#79]
The file format won't store data as compressed that is not smaller than the input buffer.

```
compressed = ZstdCompressor(level=compressionLevel).compress(buffer)
#sys.stdout.write(str(len(compressed) - len(buffer)) + "\n")
out_list[chunkRelativeBlockID] = compressed if len(compressed) < len(buffer) else buffer
```

If this happens to be the last block and that last block is smaller than the blockSize (very likely) then there is no way to identify it as being uncompressed, and the reader will always try to decompress it.

```
if self.CompressedBlockSizeList[blockID] < self.BlockSize:
	return ZstdDecompressor().decompress(self.nspf.read(self.BlockSize))
else:
	return self.nspf.read(self.BlockSize)
```

You can repro this if you forcefully store every block uncompressed, it will fail the verification.

Simple solution is to always store the last one compressed.

**Comment by nicoboss** [comment]
Thanks a lot for reporting this. I fixed it in latest NSZ v4.0 release by properly fixing this edge case.
The decision if the last block should be decompressed or copied now matches the file format specifications by comparing the decompressed block size of that specific block with its compressed size.
```decompressedBlockSize = self.BlockHeader.decompressedSize % BlockSize```
See https://github.com/nicoboss/nsz/commit/e69a6523497019d4394948d57a2f414fdbd4971d if you are interested how exactly I fixed it.
