### ISSUE TITLE
Strange error when compressing a NSP

### ISSUE THREAD

**Issue by HattDroid** [nicoboss/nsz#8]
Hi,

I was successful decompressing/compressing a few files, but one of them is giving me a weird error.

Here's the command I use:

`./nsz.py -C "file.nsp" -l 22`

Please find the output below:

compressing (level 22) path/nsz/compressor/Valfaris2 [010089700F30C000].nsp -> path/nsz/compressor/file.nsz
Adding file 010089700f30c0000000000000000008.cert 1792 bytes to NSP
Adding file 010089700f30c0000000000000000008.tik 704 bytes to NSP
Adding file 522e1cc2378cf300222c17d3cdfc7fa6.ncz 843907072 bytes to NSP
list index out of range
nut exception: list index out of range
  0%|          | 0.00/844M [00:00<?, ?B/s/s]  0%|          | 51.7k/844M [00:00<00:03, 253MB/s/s]
Traceback (most recent call last):
  File "./nsz.py", line 98, in <module>
    nut.compress(filePath, 17 if args.level is None else args.level, args.solid, args.bs, args.output, args.threads)
  File "path/nsz/compressor/nut/__init__.py", line 162, in compress
    buffer = partitions[partNr].read(CHUNK_SZ)
IndexError: list index out of range                   

The same command seems to work with my other nsps, but it fails here.
Thanks.

**Comment by blawar** [comment]
Can you try the 1.0 release and see if it fixes the issue:  https://github.com/nicoboss/nsz/releases/tag/1.0

**Comment by HattDroid** [comment]
Thanks for the quick answer.

I've pull v1.0 and tried two things:
- with keys.txt present: Exactly the same error happen
- removing keys.txt from compressor folder: No error, but the result file is not compressed, it's a 1-1 copy of the nsp (same md5sum, only nca listed in the nsz.py output, no ncz listed)

I haven't looked at the code yet, but would the error be tied to the keys.txt I use here?

**Comment by blawar** [comment]
its impossible to get that same error with 1.0.  please post the log.

**Comment by HattDroid** [comment]
Sorry for some reason I thought that master was the same as the tag 1.0.
There is no error anymore, but the compressed size of the resulting nsz is completely off. Going from 807MB to 1.3MB.

My keys.txt might not be complete I guess?

**Comment by HattDroid** [comment]
It was indeed my keys.txt file which was incomplete.
Problem solved.
Thanks for the support.
