### ISSUE TITLE
[GUI] NSZ 4.0.0 and NSZ 4.0.1 games on decompression gamelist are not getting decompressing

### ISSUE THREAD

**Issue by zahi112** [nicoboss/nsz#85]
NSZ 4.0.1 and NSZ 4.0.0 are not decompressing just crashing and closing it self.

**Comment by nicoboss** [comment]
This issue should be fixed in the latest [NSZ v4.1.0](https://github.com/nicoboss/nsz/releases/tag/4.2.0) release. Please let me know if you still experience this issue on the latest release.
