### ISSUE TITLE
Error when compressing.

### ISSUE THREAD

**Issue by dmnsv** [nicoboss/nsz#9]
nsz.py --level 22 -C "L A Noire[0100830004FB6800][US][v131072].nsp"
                        ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'
bktr reloc exception: Too many entries
bktr reloc exception: Too many entries
bktr reloc exception: Too many entries
compressing (level 22) <path>\L A Noire[0100830004FB6800][US][v131072].nsp -> <path>\L A Noire[0100830004FB6800][US][v131072].nsz
Adding file 0100830004fb68000000000000000003.cert 1792 bytes to NSP
Adding file 0100830004fb68000000000000000003.tik 704 bytes to NSP
Adding file 4b0fe8e40b498d7a4556c3d1e8433a51.ncz 14134086144 bytes to NSP

When the file is finished compressing it won't install at all.

Edit: At 77% I get the following error on the same file:

nut exception:
Traceback (most recent call last):
  File "\nsz.py", line 98, in <module>
    nut.compress(filePath, 17 if args.level is None else args.level, args.solid, args.bs, args.output, args.threads)
  File "\nut\__init__.py", line 165, in compress
    buffer += partitions[partNr].read(CHUNK_SZ - len(buffer))
MemoryError

**Comment by blawar** [comment]
update, this has been fixed.
