### ISSUE TITLE
Tasks throw exception and halt if output is corrupted when compressing with -V argument

### ISSUE THREAD

**Issue by KWottrich** [nicoboss/nsz#93]
OS: Windows 10 x64
Python installed: v3.9 (x64)
Run method: git clone repo, run nsz.py from project root folder

My use case is to compress a large directory filled with ~100 NSPs.  I ran `nsz.py -C -V -P "[path/to/folder]".  Occasionally, I would see an error message with a stack trace:
```
[VERIFY NSZ] path/to/folder/filename.nsz
[CORRUPTED]  88fc251788c7d3aba62a7663ce4504f8.ncz
nut exception: Verification detected hash missmatch
Process Process-2:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Git\nsz\nsz\__init__.py", line 39, in solidCompressTask
    verify(outFile, True, [statusReport, id], pleaseNoPrint)
  File "C:\Git\nsz\nsz\__init__.py", line 65, in verify
    NszVerify(filePath, raiseVerificationException, statusReportInfo, pleaseNoPrint)
  File "C:\Git\nsz\nsz\NszDecompressor.py", line 44, in verify
    __decompressNsz(filePath, None, False, raiseVerificationException, statusReportInfo, pleaseNoPrint)
  File "C:\Git\nsz\nsz\NszDecompressor.py", line 206, in __decompressNsz
    __decompressContainer(container, None, fileHashes, write, raiseVerificationException, statusReportInfo, pleaseNoPrint)
  File "C:\Git\nsz\nsz\NszDecompressor.py", line 91, in __decompressContainer
    raise Exception("Verification detected hash missmatch")
Exception: Verification detected hash missmatch
```
After each stack trace, one of the 4 progress bars would remain frozen at 100%.  After seeing 4 of these errors, the program appeared to completely halt.

![image](https://user-images.githubusercontent.com/3628457/117392321-6f085f80-aeb7-11eb-83f8-b9987906f466.png)
In the above screenshot, the process has been running for almost 7 hours without progressing.

I believe this is because `solidCompressTask(...)` in `__init__.py` calls `verify(...)`, where the second argument is `raiseVerificationException = True`.  This means that the verification raises an exception if the NCZ is corrupted, which eventually gets raised all the way out of the Process target method.

I think one possible fix would be to have `__decompressContainer(...)` raise a specific kind of Exception if verification fails, which can then get handled in `solidCompressTask(...)` and NOT get raised out of that method, instead of falling to the BaseException handler which raises the exception and kills the Process.

Another fix would be to add detection for dead Processes in the waiting loop to remove them from the pool and re-add new processes.  I'm not super familiar with Python thread pooling so I'm not sure what exactly that would look like.

**Comment by nicoboss** [comment]
Thanks a lot for reporting and fixing this issue! I highly appreciate it.
