### ISSUE TITLE
Specific title rejected for compressing

### ISSUE THREAD

**Issue by EkkiBrue** [nicoboss/nsz#97]
![gitbug](https://user-images.githubusercontent.com/6376844/132164739-60697192-aae8-41f7-987c-afe56842bd3a.PNG)

I have a certain file that is not able to be compressed. I renamed the file (-> 1.nsz) to make sure that filename handling is not the problem but the problems stays (see screenshot -> errno 2).

Anything I can help with ?

**Comment by Masamune3210** [comment]
For some reason the program is unable to open the file from the looks of it. If its just one particular file I'd wager there is something wrong with the file rather than the program

**Comment by EkkiBrue** [comment]
ok. Seems like the title has no ticket. Nevertheless Length an Signature are OK.

**Comment by nicoboss** [comment]
Your issue seems very strange. I never saw something like this. There is no way for me to reproduce this without more information. Can you please poste the command line arguments you used when calling nsz and the game you tried to compress?

**Comment by EkkiBrue** [comment]
No arguments to the command. 

The two most recent files I have the problem with:
[010064F016294800][v65536].nsp
[01009B90169D8000][v0].nsp

**Comment by EkkiBrue** [comment]
I tried to make sure that it´s not a too lengthy path issue.

I copied the NSPs to a different folder. Also I copied NSZ itself to a folder directly in W:\NSZ
I renamed the NSP files to 1.nsp and 2.nsp

Now dropping these files to NSZ

> Error while adding W:\nsz\1.nsp to gamelist: cannot unpack non-iterable NoneType object
>  Traceback (most recent call last):
>    File "W:\nsz\lib\site-packages\nsz\gui\GameList.py", line 127, in handledrops
>      (titleIDExtracted, versionExtracted) = FileExistingChecks.ExtractTitleIDAndVersion(fullPath, True)
>  TypeError: cannot unpack non-iterable NoneType object
> Error while adding W:\nsz\2.nsp to gamelist: cannot unpack non-iterable NoneType object
>  Traceback (most recent call last):
>    File "W:\nsz\lib\site-packages\nsz\gui\GameList.py", line 127, in handledrops
>      (titleIDExtracted, versionExtracted) = FileExistingChecks.ExtractTitleIDAndVersion(fullPath, True)
>  TypeError: cannot unpack non-iterable NoneType object
> Error while adding W:\nsz\1.nsp to gamelist: cannot unpack non-iterable NoneType object
>  Traceback (most recent call last):
>    File "W:\nsz\lib\site-packages\nsz\gui\GameList.py", line 127, in handledrops
>      (titleIDExtracted, versionExtracted) = FileExistingChecks.ExtractTitleIDAndVersion(fullPath, True)
>  TypeError: cannot unpack non-iterable NoneType object
> Error while adding W:\nsz\2.nsp to gamelist: cannot unpack non-iterable NoneType object
>  Traceback (most recent call last):
>    File "W:\nsz\lib\site-packages\nsz\gui\GameList.py", line 127, in handledrops
>      (titleIDExtracted, versionExtracted) = FileExistingChecks.ExtractTitleIDAndVersion(fullPath, True)
>  TypeError: cannot unpack non-iterable NoneType object
> Error while adding W:\nsz\1.nsp to gamelist: cannot unpack non-iterable NoneType object
>  Traceback (most recent call last):
>    File "W:\nsz\lib\site-packages\nsz\gui\GameList.py", line 127, in handledrops
>      (titleIDExtracted, versionExtracted) = FileExistingChecks.ExtractTitleIDAndVersion(fullPath, True)
>  TypeError: cannot unpack non-iterable NoneType object
> Error while adding W:\nsz\2.nsp to gamelist: cannot unpack non-iterable NoneType object
>  Traceback (most recent call last):
>    File "W:\nsz\lib\site-packages\nsz\gui\GameList.py", line 127, in handledrops
>      (titleIDExtracted, versionExtracted) = FileExistingChecks.ExtractTitleIDAndVersion(fullPath, True)
>  TypeError: cannot unpack non-iterable NoneType object

Renamed files back to their original name, dropping on NSZ:

> Solid compressing (level 22) W:\nsz\Neon Hell [01009B90169D8000][v0].nsp -> W:\nsz\Neon Hell [01009B90169D8000][v0].nsz
> [ADDING]     01009b90169d8000000000000000000d.cert 1792 bytes to NSP
> [ADDING]     01009b90169d8000000000000000000d.tik 704 bytes to NSP
> Traceback (most recent call last):
>   File "W:\nsz\lib\site-packages\nsz\SolidCompressor.py", line 132, in solidCompressNsp
>     processContainer(container, nsp, compressionLevel, threads, stusReport, id, pleaseNoPrint)
>   File "W:\nsz\lib\site-packages\nsz\SolidCompressor.py", line 29, in processContainer
>     offsetFirstSection = sortedFs(nspf)[0].offset
> IndexError: list index out of range
> 
> [VERIFY NSZ] W:\nsz\Neon Hell [01009B90169D8000][v0].nsz
> Solid compressing (level 22) W:\nsz\QUByte Classics - The Immortal by PIKO [010064F016294800][v65536].nsp -> W:\nsz\QUByte Classics - The Immortal by PIKO [010064F016294800][v65536].nsz
> nut exception: [Errno 2] No such file or directory: 'W:\\nsz\\Neon Hell [01009B90169D8000][v0].nsz'
> Traceback (most recent call last):
>   File "W:\nsz\lib\site-packages\nsz\SolidCompressor.py", line 132, in solidCompressNsp
>     processContainer(container, nsp, compressionLevel, threads, stusReport, id, pleaseNoPrint)
>   File "W:\nsz\lib\site-packages\nsz\SolidCompressor.py", line 29, in processContainer
>     offsetFirstSection = sortedFs(nspf)[0].offset
> IndexError: list index out of range
> 
> [VERIFY NSZ] W:\nsz\QUByte Classics - The Immortal by PIKO [010064F016294800][v65536].nsz
> nut exception: [Errno 2] No such file or directory: 'W:\\nsz\\QUByte Classics - The Immortal by PIKO [010064F016294800][v65536].nsz'
> Process Process-3:
> Process Process-2:
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "W:\nsz\lib\multiprocessing\process.py", line 297, in _bootstrap
>     self.run()
>   File "W:\nsz\lib\multiprocessing\process.py", line 297, in _bootstrap
>     self.run()
>   File "W:\nsz\lib\multiprocessing\process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "W:\nsz\lib\multiprocessing\process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "W:\nsz\lib\site-packages\nsz\__init__.py", line 39, in solidCompressTask
>     verify(outFile, True, [statusReport, id], pleaseNoPrint)
>   File "W:\nsz\lib\site-packages\nsz\__init__.py", line 39, in solidCompressTask
>     verify(outFile, True, [statusReport, id], pleaseNoPrint)
>   File "W:\nsz\lib\site-packages\nsz\__init__.py", line 65, in verify
>     NszVerify(filePath, raiseVerificationException, statusReportInfo, pleaseNoPrint)
>   File "W:\nsz\lib\site-packages\nsz\__init__.py", line 65, in verify
>     NszVerify(filePath, raiseVerificationException, statusReportInfo, pleaseNoPrint)
>   File "W:\nsz\lib\site-packages\nsz\NszDecompressor.py", line 44, in verify
>     __decompressNsz(filePath, None, False, raiseVerificationException, statusReportInfo, pleaseNoPrint)
>   File "W:\nsz\lib\site-packages\nsz\NszDecompressor.py", line 44, in verify
>     __decompressNsz(filePath, None, False, raiseVerificationException, statusReportInfo, pleaseNoPrint)
>   File "W:\nsz\lib\site-packages\nsz\NszDecompressor.py", line 192, in __decompressNsz
>     fileHashes = FileExistingChecks.ExtractHashes(filePath)
>   File "W:\nsz\lib\site-packages\nsz\NszDecompressor.py", line 192, in __decompressNsz
>     fileHashes = FileExistingChecks.ExtractHashes(filePath)
>   File "W:\nsz\lib\site-packages\nsz\FileExistingChecks.py", line 14, in ExtractHashes
>     container.open(str(gamePath), 'rb')
>   File "W:\nsz\lib\site-packages\nsz\FileExistingChecks.py", line 14, in ExtractHashes
>     container.open(str(gamePath), 'rb')
>   File "W:\nsz\lib\site-packages\nsz\Fs\Nsp.py", line 197, in open
>     super(Nsp, self).open(path or self.path, mode, cryptoType, cryptoKey, cryptoCounter)
>   File "W:\nsz\lib\site-packages\nsz\Fs\Nsp.py", line 197, in open
>     super(Nsp, self).open(path or self.path, mode, cryptoType, cryptoKey, cryptoCounter)
>   File "W:\nsz\lib\site-packages\nsz\Fs\Pfs0.py", line 132, in open
>     r = super(Pfs0, self).open(path, mode, cryptoType, cryptoKey, cryptoCounter)
>   File "W:\nsz\lib\site-packages\nsz\Fs\Pfs0.py", line 132, in open
>     r = super(Pfs0, self).open(path, mode, cryptoType, cryptoKey, cryptoCounter)
>   File "W:\nsz\lib\site-packages\nsz\Fs\BaseFs.py", line 96, in open
>     r = super(BaseFs, self).open(path, mode, cryptoType, cryptoKey, cryptoCounter)
>   File "W:\nsz\lib\site-packages\nsz\Fs\BaseFs.py", line 96, in open
>     r = super(BaseFs, self).open(path, mode, cryptoType, cryptoKey, cryptoCounter)
>   File "W:\nsz\lib\site-packages\nsz\Fs\File.py", line 210, in open
>     self.f = open(path, mode)
>   File "W:\nsz\lib\site-packages\nsz\Fs\File.py", line 210, in open
>     self.f = open(path, mode)
> FileNotFoundError: [Errno 2] No such file or directory: 'W:\\nsz\\Neon Hell [01009B90169D8000][v0].nsz'
> FileNotFoundError: [Errno 2] No such file or directory: 'W:\\nsz\\QUByte Classics - The Immortal by PIKO [010064F016294800][v65536].nsz'

Very strange behaviour. I wonder why renaming leads to this...

**Comment by EkkiBrue** [comment]
ok. Sorry - seems my fail... updateing prod.keys makes all run well again so far...
