### ISSUE TITLE
Ability to compress Multicontent NSPs?

### ISSUE THREAD

**Issue by RinMaru** [nicoboss/nsz#99]
I've noticed recently that nsps that have dlc and updates merged can't be compressed is there a reason for this and is it something that can be implemented?

**Comment by Masamune3210** [comment]
The format itself supports it, as NSC_BUILDER can compress multicontent packages

**Comment by RinMaru** [comment]
> The format itself supports it, as NSC_BUILDER can compress multicontent packages

I've been using nsc builder and any Multicontent nsp can't be compressed at all it gives errors even though the game isn't corrupted and all checks out

**Comment by blawar** [comment]
A properly created multi content nsp can be compressed.  Usually these multicontent xci/nsp files you see are not proper/clean.

 In either case, you would need to provide more info to properly debug this.

post the nsz.py -i file.nsp output

**Comment by RinMaru** [comment]
i dont see any such files im using the exe not python script. at any rate my usual way of merging is using NSC Builder and repacking as NSP with unedited eshop files

**Comment by RinMaru** [comment]
> A properly created multi content nsp can be compressed. Usually these multicontent xci/nsp files you see are not proper/clean.
> 
> In either case, you would need to provide more info to properly debug this.
> 
> post the nsz.py -i file.nsp output

Just in case this is user error is there a specific way to merge nsps correctly?

**Comment by blawar** [comment]
> i dont see any such files im using the exe not python script. at any rate my usual way of merging is using NSC Builder and repacking as NSP with unedited eshop files

I am not familiar with NSC_builder, but if they are modified nca’s, then it should work.

We need the -i output and any error messages you may be receiving.

**Comment by RinMaru** [comment]
> > i dont see any such files im using the exe not python script. at any rate my usual way of merging is using NSC Builder and repacking as NSP with unedited eshop files
> 
> I am not familiar with NSC_builder, but if they are modified nca’s, then it should work.
> 
> We need the -i output and any error messages you may be receiving.

na they are merged nsps Base nsp and update nsp. should i just copy the txt in the cmd window?

**Comment by RinMaru** [comment]
i seem to have fixed the issue it was a permission error when accessing files from a diff drive. I would still like to know how you personally merge the files so i may learn

**Comment by hyoretsu** [comment]
I also have this problem, none of the NSP's I merged with Switch Army Knife is able to be compressed.

```
Failed to extract TitleID/Version from filename "Super Mario Odyssey.nsp". Use -p to extract from Cnmt.

could not find title key 0100000000010000!
could not find title key 0100000000010000!
```
```
Traceback (most recent call last):
  File "C:\Users\hyore\AppData\Roaming\Python\Python310\site-packages\nsz\SolidCompressor.py", line 132, in solidCompressNsp
    processContainer(container, nsp, compressionLevel, threads, stusReport, id, pleaseNoPrint)
  File "C:\Users\hyore\AppData\Roaming\Python\Python310\site-packages\nsz\SolidCompressor.py", line 55, in processContainer
    header += fs.cryptoKey
TypeError: can't concat NoneType to bytes
```

**Comment by RinMaru** [comment]
> I also have this problem, none of the NSP's I merged with Switch Army Knife is able to be compressed. (by NSZ, NSC_Builder or SAK)
> 
> ```
> Failed to extract TitleID/Version from filename "Super Mario Odyssey.nsp". Use -p to extract from Cnmt.
> 
> could not find title key 0100000000010000!
> could not find title key 0100000000010000!
> ```
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\hyore\AppData\Roaming\Python\Python310\site-packages\nsz\SolidCompressor.py", line 132, in solidCompressNsp
>     processContainer(container, nsp, compressionLevel, threads, stusReport, id, pleaseNoPrint)
>   File "C:\Users\hyore\AppData\Roaming\Python\Python310\site-packages\nsz\SolidCompressor.py", line 55, in processContainer
>     header += fs.cryptoKey
> TypeError: can't concat NoneType to bytes
> ```

yea i just use NSC Builder to compress and merge stuff. though nsz always says games are currupt afterwards but show up fine elseware

**Comment by Masamune3210** [comment]
its because nsc_builder doesnt update one of the hashes iirc, but the files are fine. Tools other than nsc_builder just spit them out because they are trying to be as through in their validation as possible, the switch doesn't care with sigpatches, as long as the file is valid it will run it

**Comment by jsboige** [comment]
> I also have this problem, none of the NSP's I merged with Switch Army Knife is able to be compressed. (by NSZ, NSC_Builder or SAK)
> 
> ```
> Failed to extract TitleID/Version from filename "Super Mario Odyssey.nsp". Use -p to extract from Cnmt.
> 
> could not find title key 0100000000010000!
> could not find title key 0100000000010000!
> ```
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\hyore\AppData\Roaming\Python\Python310\site-packages\nsz\SolidCompressor.py", line 132, in solidCompressNsp
>     processContainer(container, nsp, compressionLevel, threads, stusReport, id, pleaseNoPrint)
>   File "C:\Users\hyore\AppData\Roaming\Python\Python310\site-packages\nsz\SolidCompressor.py", line 55, in processContainer
>     header += fs.cryptoKey
> TypeError: can't concat NoneType to bytes
> ```

I'm also having the exact same issue and error messages with merged NSPs from DBI's MTP responder, so I guess there is a broader issue and easy repro that might be worth investigating.

**Comment by blawar** [comment]
What are the filenames inside of the NSP?  specifically the names of the *.tik files? @jsboige

**Comment by jsboige** [comment]
> What are the filenames inside of the NSP? specifically the names of the *.tik files? @jsboige

Here is a samples of a faulty merged NSP's content files names:

```
0100a6b014926000000000000000000b.cert
0100a6b014926000000000000000000b.tik
0100a6b014926800000000000000000b.cert
0100a6b014926800000000000000000b.tik
```

another one

```
0100fe1011400000000000000000000b.cert
0100fe1011400000000000000000000b.tik
0100fe1011400800000000000000000b.cert
0100fe1011400800000000000000000b.tik
```

and here is a standard non-fused one that does work:

```
0100d4c00ee0c000000000000000000a.cert
0100d4c00ee0c000000000000000000a.tik
```

Note that I didn't do anything fancy and simply used DBI to download the fused NSP as they were listed at the root SD directory using MTP responder.
